name: GRPS382
version: "0.0.1"
license: "Artistic-2.0"
date: 2022-05-14
description: |
    Library of the groups of order 3^8*2

authors:
    - name: David Burrell
      url: https://davidburrell.github.io/

maintainers:
    - name: David Burrell
      url: https://davidburrell.github.io/

GAP: ">= 4.11"

www: https://davidburrell.github.io/GRPS382/
readme: README.md
packageinfo: https://davidburrell.github.io/GRPS382/PackageInfo.g
github: https://github.com/davidburrell/GRPS382

downloads:
    - name: .tar.gz
      url: https://github.com/davidburrell/GRPS382/archive/refs/tags/v0.0.1.tar.gz
    - name: .zip
      url: https://github.com/davidburrell/GRPS382/archive/refs/tags/v0.0.1.zip

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bur22</span>]   <b class='BibAuthor'>Burrell, D.</b>,
     <i class='BibTitle'>GRPS382, Library of the groups of order 3^8*2,
             Version 0.0.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://davidburrell.github.io/GRPS382/">https://davidburrell.github.io/GRPS382/</a></span>.
    </p>
    

bibtex: |
    @misc{ GRPS3820.0.1,
      author =           {Burrell, D.},
      title =            {{GRPS382}, Library of the groups of order 3\texttt{\symbol{94}}8*2, {V}ersion 0.0.1},
      month =            {May},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href {https://davidburrell.github.io/GRPS382/} {\texttt{https://davidburrell.github.io/}\discretionary {}{}{}\texttt{GRPS382/}}},
      printedkey =       {Bur22}
    }

